services:
  - type: web
    name: newsly-backend
    env: python
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn backend.wsgi:application
    workingDir: backend
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: newsly-db
          property: connectionString
