services:
  - type: web
    name: newsly-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: django-insecure-your-secret-key-here
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: newsly-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: coder0214h@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: onuopumpcgbwolbo
