services:
  - type: web
    name: newsly-ai
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: django-insecure-your-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: newsly-db
          property: connectionString
      - key: OPENAI_API_KEY
        value: sk-your-openai-api-key-here
      - key: NEWSDATA_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

databases:
  - name: newsly-db
    databaseName: newsly
    user: newsly
