export default function TermsAndConditions() {
  return (
    <div className="max-w-4xl mx-auto p-6 text-gray-800">
      <h1 className="text-3xl font-bold mb-4 ml-[230px]">Terms and Conditions</h1>
      <div className="space-y-4 h-[500px]  pr-2 text-justify leading-7 text-blue-800">
        <p>
          Welcome to Newsly.AI. Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the platform. By accessing or using any part of the service, you agree to be bound by these terms. If you disagree with any part, you may not access the service.
        </p>

        <p>
          <strong>1. Eligibility </strong>  
          You must be at least 13 years of age to use this service. By using the platform, you represent and warrant that you meet this requirement and that you are fully able and competent to enter into and comply with these Terms.
        </p>

        <p>
          <strong>2. User Accounts </strong>  
          When you create an account with us, you must provide accurate, complete, and current information at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.
        </p>

        <p>
          <strong>3. Content Ownership </strong>  
          All news articles, summaries, and related content provided through Newsly.AI are the property of their respective sources. The summaries generated by Newsly.AI are the intellectual property of the platform and may not be redistributed without explicit permission.
        </p>

        <p>
          <strong>4. Acceptable Use </strong>  
          You agree not to use the platform for any unlawful purpose or in a way that could damage, disable, or impair our services. This includes scraping data, reverse engineering the application, or misusing content.
        </p>

        <p>
          <strong>5. Privacy Policy </strong>  
          Your privacy is important to us. Please read our Privacy Policy to understand how we collect, use, and disclose your personal data. By using our service, you agree to our privacy practices.
        </p>

        <p>
          <strong>6. Modification of Terms </strong>  
          We reserve the right to update or change our Terms at any time. Continued use of the service after changes are made implies acceptance of the new Terms.
        </p>

        <p>
          <strong>7. Service Availability </strong>  
          We strive to keep Newsly.AI running smoothly. However, we do not guarantee uninterrupted or error-free service and are not liable for any downtime or loss of data.
        </p>

        <p>
          <strong>8. Termination </strong>  
          We may suspend or terminate your access to the service without prior notice if we believe you have violated these Terms or engaged in conduct that may harm us or other users.
        </p>

        <p>
          <strong>9. Limitation of Liability </strong>  
          In no event shall Newsly.AI, nor its creators, be liable for any indirect, incidental, special, or consequential damages resulting from the use of the platform.
        </p>

        <p>
          <strong>10. Governing Law </strong>  
          These Terms shall be governed and construed in accordance with the laws of your jurisdiction, without regard to its conflict of law provisions.
        </p>

        <p>
          <strong>11. Contact Information </strong>  
          If you have any questions about these Terms, you may contact us at support@newsly.ai.
        </p>

        <p>
          <strong>12. Final Word </strong>  
          By using Newsly.AI, you acknowledge that you’ve read, understood, and agreed to these Terms and Conditions. If not, we kindly ask you to refrain from using the service.
        </p>
      </div>
    </div>
  );
}