# Generated by Django 5.2.1 on 2025-05-26 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
