# Generated by Django 5.2.1 on 2025-05-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_customuser_preferred_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('url', models.URLField(unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('reading_difficulty', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('is_breaking', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.topic')),
            ],
        ),
    ]
