# Generated by Django 5.2.1 on 2025-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_topic_article_readhistory_savedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to='core.topic'),
        ),
    ]
