# Generated by Django 5.2.1 on 2025-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_interests_customuser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
